Update tutorial text to reflect custom keybinds
CaosCreations/JumpingJax pull request #189
Opened 2020-12-14 18:19 UTC by maxwellpark

2020-12-14 18:20 UTC, maxwellpark commented
Committed Hop3 tutorial text for testing purposes

2020-12-15 00:21 UTC, ambid17 requested changes
God damn this was some beautiful code. Really well done. Love the string extensions. However, i tested this on hop 2, and changed the jump key to G and it didn't update

2020-12-15 13:03 UTC, maxwellpark commented
All the hops should work now.

2020-12-15 20:11 UTC, ambid17 approved these changes

2020-12-15 20:11 UTC, merged