Set level editor play tester position to first checkpoint if there is one.
CaosCreations/JumpingJax pull request #249
Opened 2021-01-30 19:53 UTC by maxwellpark

2021-01-30 23:14 UTC, ambid17 requested changes

2021-01-30 23:14 UTC, ambid17 commented on Assets/Scripts/Utils/LevelEditorUtils.cs
> +public class LevelEditorUtils : MonoBehaviour
doesnt need to be monobehavior

2021-01-30 23:14 UTC, ambid17 commented on Assets/Scripts/LevelEditor/LevelEditorHUD.cs
> +        LevelEditorObject firstCheckpoint = LevelEditorUtils
should be able to just find checkpoints instead of searching object data

2021-01-31 00:18 UTC, maxwellpark commented on Assets/Scripts/Utils/LevelEditorUtils.cs
> +public class LevelEditorUtils : MonoBehaviour
cant use that find method without it

2021-02-01 01:47 UTC, ambid17 approved these changes

2021-02-01 02:45 UTC, merged